import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";

import "./globals.css";
import styles from './layout.module.css';
import Sidebar from "./components/Sidebar/Sidebar";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";


const notoSans = Noto_Sans({ subsets: ["cyrillic", "latin"], weight: ["300", "400", "500", "700"] });

export const metadata: Metadata = {
  title: "Top-app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSans.className}>
        <div className={styles.container}>
          <Header  className={styles.header}/>
          <Sidebar className={styles.sidebar} />
          <div className={styles.body}>
            {children}
          </div>
          <Footer  className={styles.footer}/>
        </div>
      </body>
    </html>
  );
}
